modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="homing_ender_eye" #mandatory
version = "${version}" #mandatory
displayName="Homing Ender Eye" #mandatory
displayURL="https://github.com/DragonsPlusMinecraft/HomingEnderEye" #optional
logoFile="logo.png"
authors="MarbleGateKeeper" #optional
description='''
Oh Alex...The eye of ender did not disappear or break. It just went to the path homing.
'''
[[dependencies.homing_ender_eye]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[46,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.homing_ender_eye]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"